-- GENERATED by scripts/gen-seed.py from data/rubric.txt and the JDs. Safe to re-run (never deletes).
insert into roles (code, title, jd_text) values ('PM', 'Product Manager', $q$Kargo   ·   Mumbai   ·   Series A

Product Manager
Full-time  ·  In-office, Mumbai  ·  Reports to: Arjun Mehta, Founder
About Kargo
Kargo builds software for mid-sized freight forwarders and 3PLs — the companies that move goods across borders and between ports, warehouses, and buyers. Our platform automates the parts of their operation that still run on spreadsheets and WhatsApp chains: shipment tracking, documentation, and carrier coordination. We are Series A, 40 people, and scaling to 70 by December.
Why This Role Exists
We have one product, a growing customer base, and no dedicated PM function yet. The person in this role will be the first PM at Kargo focused on our core platform — the day-to-day tool that operations teams at freight forwarders live inside. There is a lot to build, and a lot to understand about how our customers actually work. Both are connected.
What You'll Own
—  The product roadmap for Kargo's core operations platform: shipment tracking, documentation workflows, and real-time status visibility for freight forwarders and their customers
—  Customer discovery — understanding where the platform is helping and where it isn't, from the people who use it daily
—  Working directly with the engineering team to define what gets built, in what order, and why
—  The rhythms a PM function needs: how we decide what to prioritise, how we track whether something worked, how decisions are communicated across the team
What Success Looks Like at 6 Months
—  You have shipped at least two features that customers use without being asked to — not because we asked, because they found them useful
—  You can tell Arjun, without hesitation, what the three most important things to build next are and why
—  The engineering team knows what they are building three sprints out
—  You have spent time inside freight forwarding operations — not just over calls, but in the rooms where the work actually happens
What We're Looking For
—  2–4 years of product management experience, ideally at a company building for the first time rather than maintaining what already exists
—  Comfort operating without structure — no PM handbook, no design system, no sprint template. You'll build those
—  Evidence that you've shipped things, killed things, and learned from both — preferably in short cycles
—  Genuine curiosity about how operations work at ground level. What does a freight forwarder's morning actually look like? What breaks? What slows them down?
—  Mumbai-based or willing to relocate. This role is in-office
What Kargo Offers
—  Real ownership, early. You will be the PM — not one of ten
—  Direct access to the founding team and to customers
—  A product with genuine complexity and users who depend on it for their daily operations
—  The experience of building a product function from scratch, not joining one that already exists
Kargo is an equal opportunity employer. All roles are in-office, Mumbai. If you are relocating, we will work with you on timing.$q$)
  on conflict (code) do update set title = excluded.title, jd_text = excluded.jd_text;
insert into roles (code, title, jd_text) values ('SPM', 'Senior Product Manager', $q$Kargo   ·   Mumbai   ·   Series A

Senior Product Manager
Full-time  ·  In-office, Mumbai  ·  Reports to: Arjun Mehta, Founder
About Kargo
Kargo builds software for mid-sized freight forwarders and 3PLs — the companies that move goods across borders and between ports, warehouses, and buyers. Our platform automates shipment tracking, documentation, and carrier coordination. We are Series A, 40 people, and scaling to 70 by December.
Why This Role Exists
As we scale, Kargo's product is becoming more complex. More carrier integrations. More customer-specific configurations. More data flowing between Kargo and the systems our customers already use. We need someone who can own the harder parts of the platform: the decisions that have consequences we will feel two years from now, not just in the next sprint. This person will also be the most senior PM at Kargo, which means they will help shape what the product function looks like as we grow.
What You'll Own
—  The integration and data layer of Kargo's platform: how we connect with carrier systems, port portals, ERP environments, and the freight management tools our customers already operate
—  The hard architectural product calls — what we build, what we configure, what we stay away from
—  Reliability and data quality standards that freight forwarders can stake their operations on
—  Working across sales, engineering, and customer operations to understand which integrations unlock new customers and which gaps are losing them
—  Helping define the practices, decision frameworks, and ways of working the PM function will run on as Kargo grows
What Success Looks Like at 6 Months
—  You own an integration roadmap that engineering, sales, and Arjun all agree on and trust — and that has not changed three times in six weeks
—  At least one major integration has shipped that opened a new customer segment or unblocked a stalled deal
—  You have a clear, defensible point of view on what Kargo should build versus configure versus not touch — and the team knows what it is
—  The product function has clearer standards for what good PM work looks like, because you have demonstrated it
What We're Looking For
—  5–8 years of product management experience, with clear evidence of owning a product area without a layer of senior PMs above you making the calls
—  Experience with platform products, integration layers, or products that have to work inside complex existing technical environments
—  Proven ability to make calls in ambiguous situations and live with the consequences — at Kargo there is no committee that approves product decisions
—  Time spent at an early-stage company, or strong evidence that you have operated in environments where the rules were not written yet
—  Familiarity with how operations-heavy industries work at ground level — logistics, supply chain, or adjacent domains — is a genuine advantage here, not a nice-to-have
—  Mumbai-based or willing to relocate. This role is in-office
What Kargo Offers
—  A role that could become Head of Product as we scale. We are not offering a title — we are offering the actual work
—  Direct access to Arjun and the founding team
—  A product with real complexity, real customers, and real operational stakes
—  The chance to build a PM function rather than join one
Kargo is an equal opportunity employer. All roles are in-office, Mumbai. If you are relocating, we will work with you on timing.$q$)
  on conflict (code) do update set title = excluded.title, jd_text = excluded.jd_text;
insert into rubric_criteria (role_code, sort, name, description, weight) values ('PM', 1, $q$Unasked Fix$q$, $q$The CV names a specific problem that was nobody's assigned job, such as a process, tool, checklist or workflow gap, and says the candidate built the fix themselves. It says why they noticed it, for example because they were doing or watching the work. Score high if all three are present: a named problem, "no one asked," and something concrete that was built. Score low if the CV only lists features shipped from a roadmap.$q$, 30)
  on conflict (role_code, name) do update set sort = excluded.sort, description = excluded.description, weight = excluded.weight;
insert into rubric_criteria (role_code, sort, name, description, weight) values ('PM', 2, $q$Proof of Uptake$q$, $q$For that fix, the CV states how many people used it, in what time, and whether it lasted, for example "30 colleagues in the first month" or "still in use / became team standard." Use was voluntary. Score high for a number plus a timeframe plus evidence of durability. Score low for adoption claims with no count or timeframe ("well received," "improved alignment").$q$, 30)
  on conflict (role_code, name) do update set sort = excluded.sort, description = excluded.description, weight = excluded.weight;
insert into rubric_criteria (role_code, sort, name, description, weight) values ('PM', 3, $q$Owned Miss$q$, $q$The CV describes at least one thing that went wrong, whether their own decision, a lost deal, a failed launch or an outage. It states the root cause and points to something durable that came out of it, such as a written post-mortem, a changed standard, or follow-ups completed. Score high if a cause and a lasting change are both named. A CV with only successes scores zero here.$q$, 20)
  on conflict (role_code, name) do update set sort = excluded.sort, description = excluded.description, weight = excluded.weight;
insert into rubric_criteria (role_code, sort, name, description, weight) values ('PM', 4, $q$Early Call$q$, $q$The CV shows the candidate acting on a small or early signal before it became a crisis, and states the lead time or trigger, such as "flagged 30-45 days before renewal" or "redirected after 30 days of usage data." Score high for a named signal, a stated lead time and an action taken. Score low if results appear only as after-the-fact aggregates.$q$, 20)
  on conflict (role_code, name) do update set sort = excluded.sort, description = excluded.description, weight = excluded.weight;
insert into rubric_criteria (role_code, sort, name, description, weight) values ('SPM', 1, $q$Unasked Fix$q$, $q$Meets everything the PM version of this criterion asks for (The CV names a specific problem that was nobody's assigned job, such as a process, tool, checklist or workflow gap, and says the candidate built the fix themselves. It says why they noticed it, for example because they were doing or watching the work. Score high if all three are present: a named problem, "no one asked," and something concrete that was built. Score low if the CV only lists features shipped from a roadmap.) and, in addition, the fix reached beyond the candidate's own team, into other teams, functions or clients. Nobody sponsored or approved it beforehand. It changed a standard, process or system that others now depend on. Score high only if the CV shows a cross-team reach and a change that outlasted the original problem. A fix used only by the candidate's own immediate team caps at a mid score.$q$, 25)
  on conflict (role_code, name) do update set sort = excluded.sort, description = excluded.description, weight = excluded.weight;
insert into rubric_criteria (role_code, sort, name, description, weight) values ('SPM', 2, $q$Proof of Uptake$q$, $q$Adoption is quantified and voluntary, and it spread beyond the people the candidate directly managed or sat beside. For example, other regional teams adopted it on their own, or it became the default method. Score high for a count, a timeframe and evidence of spread. Uptake within the candidate's own team caps at a mid score.$q$, 20)
  on conflict (role_code, name) do update set sort = excluded.sort, description = excluded.description, weight = excluded.weight;
insert into rubric_criteria (role_code, sort, name, description, weight) values ('SPM', 3, $q$Owned Miss$q$, $q$The miss traces to a decision the candidate made or owned, not a vendor's or a colleague's error. The CV names the root cause, shows the candidate wrote it up for others, and shows that the write-up changed how the team or company works afterward (a new pre-qualification step, a new review practice). Score high only when the cause, the record and the changed practice are all visible. An honest post-mortem with no change afterward caps at mid.$q$, 25)
  on conflict (role_code, name) do update set sort = excluded.sort, description = excluded.description, weight = excluded.weight;
insert into rubric_criteria (role_code, sort, name, description, weight) values ('SPM', 4, $q$Early Call$q$, $q$The candidate acted on an early signal that contradicted what stakeholders or customers were asking for, and accepted a cost to do it, such as redirecting planned work or losing a near-term commitment. The CV states the signal, the lead time, what was given up, and what happened next. Score high for all four. Early action that cost nothing and met no resistance caps at mid.$q$, 30)
  on conflict (role_code, name) do update set sort = excluded.sort, description = excluded.description, weight = excluded.weight;
insert into settings (key, value) values ('scoring_notes', $q$- "Uptake" and "Owned Miss" are the discriminators. Every CV claims initiative and results. Very few give a user count with a timeframe, or admit a miss with a root cause.
- Cap-at-mid rules make the SPM bar higher. They test how far the candidate's work travelled and what it cost them, rather than asking for more years or a bigger title.
- CVs are written differently. A strong candidate may leave out a miss because they were coached to. If a CV is silent on Owned Miss, ask about it in the interview before scoring it zero.$q$)
  on conflict (key) do update set value = excluded.value;
insert into settings (key, value) values ('patterns', $q$Pattern 1: They built something nobody assigned, and the people doing the work adopted it quickly, with numbers attached.
- Rohan: Excel tracker spread across a 12-person team in two weeks; Bill of Lading tool used by 30 colleagues in a month.
- Sunita: redesigned team intake workflow over a weekend, kept permanently; SOPs adopted in full within 60 days.
- Lavanya: visibility dashboard adopted by 2 other regional teams; same-day triage process that hadn't existed before.
- Meghna: onboarding checklist and 30-60-90 framework became the CS team standard.
- Aditya: case study programme became primary sales collateral.
Lower-rated CVs show this only weakly (vague adoption, or stays within own function).

Pattern 2: They put the bad news on the record.
- Lavanya: internal and customer-facing outage post-mortem, follow-ups closed.
- Aditya: documented root cause of a lost 4-month account; became standard pre-qualification practice.
- Meghna: wrote bug report for undocumented limitation, managed customer communication through 6-week fix.
- Sunita: found four documentation gaps before an inspection.
- Rohan: identified vendor reliability problems and led migration away.
Vikram's, Rahul's and Preetham's CVs contain wins only.

Pattern 3: They acted on an early, small signal instead of waiting for the lagging number, and they state the lead time.
- Meghna: flagged at-risk accounts 30-45 days before renewal.
- Lavanya: redirected a sprint within 30 days on early usage data.
- Sunita: audited before the inspection.
- Rohan: noticed a repetitive manual check and prototyped a fix that weekend.
Lower-rated CVs mostly report after-the-fact aggregates.$q$)
  on conflict (key) do update set value = excluded.value;
insert into settings (key, value) values ('threshold', '1'), ('top_n', '5')
  on conflict (key) do nothing;
