"""Builds supabase/seed.sql from data/rubric.txt and the two JD text files.
Run: python scripts/gen-seed.py   (re-run whenever the rubric or JDs change)"""
import re, pathlib
root = pathlib.Path(__file__).resolve().parent.parent
rubric = (root / "data/rubric.txt").read_text(encoding="utf8")

def dq(s): return "$q$" + s.strip() + "$q$"

sections = re.split(r"=+\nRUBRIC: (.+?) \(weights total 100%\)\n=+\n", rubric)
# sections: [pre, title1, body1, title2, body2, ...]
roles = {"PRODUCT MANAGER": "PM", "SENIOR PRODUCT MANAGER": "SPM"}
crit = {}
for i in range(1, len(sections), 2):
    code = roles[sections[i].strip()]
    body = sections[i + 1].split("=====")[0]
    items = re.findall(
        r"Criterion name: (.+?)\nWhat a strong candidate looks like: (.+?)\nWeight: (\d+)%", body, re.S)
    assert sum(int(w) for _, _, w in items) == 100, code
    crit[code] = items

notes = rubric.split("SCORING NOTES\n=====================================================\n")[1].strip()
titles = {"PM": "Product Manager", "SPM": "Senior Product Manager"}
jd = {"PM": (root / "data/jd_pm.txt").read_text(encoding="utf8"),
      "SPM": (root / "data/jd_spm.txt").read_text(encoding="utf8")}

out = ["-- GENERATED by scripts/gen-seed.py from data/rubric.txt and the JDs. Safe to re-run.\n"]
for code in ("PM", "SPM"):
    out.append(f"insert into roles (code, title, jd_text) values ('{code}', '{titles[code]}', {dq(jd[code])})\n"
               f"  on conflict (code) do update set title = excluded.title, jd_text = excluded.jd_text;\n")
out.append("delete from rubric_criteria;\n")
pm_desc = {name: " ".join(d.split()) for name, d, _ in crit["PM"]}
for code in ("PM", "SPM"):
    for n, (name, desc, w) in enumerate(crit[code], 1):
        # rubric.txt says "As above, but ..." for one SPM criterion; spell out what "above" means so it stands alone.
        if desc.strip().startswith("As above, but"):
            rest = desc.strip()[len("As above, but"):].strip()
            desc = f"Meets everything the PM version of this criterion asks for ({pm_desc[name]}) and, in addition, {rest}"
        out.append("insert into rubric_criteria (role_code, sort, name, description, weight) values "
                   f"('{code}', {n}, {dq(name)}, {dq(' '.join(desc.split()))}, {w});\n")
out.append(f"insert into settings (key, value) values ('scoring_notes', {dq(notes)})\n"
           "  on conflict (key) do update set value = excluded.value;\n")
out.append("insert into settings (key, value) values ('threshold', '60'), ('top_n', '5')\n"
           "  on conflict (key) do nothing;\n")
(root / "supabase/seed.sql").write_text("".join(out), encoding="utf8")
print({k: [(n, w) for n, _, w in v] for k, v in crit.items()})
